# Generated by Django 3.0.8 on 2020-07-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_rating', models.IntegerField()),
            ],
        ),
    ]
